# Basic site info
title:              "Gaurav Shahane •••"
description:        "Data Science Blog"
keywords:           "Gaurav Shahane, personal blog, Data Science, Machine Learning, Statistics, Python"
logo_text:          "Gaurav Shahane"
show_tagline:       true # edit file in /_includes/tagline.html
show_social_icons:  true # edit file in /_includes/social_links.html
og_locale:          "en_US"
cover:              "/assets/logo.png" # site image cover

# Site URL settings
#url:                https://heiswayi.nrird.com # main url
#baseurl:            null # for gh-pages
#enforce_ssl:        heiswayi.nrird.com

# Site author info
author:
  name:             "Gaurav Shahane"
  email:            gshahane@terpmail.umd.edu
  github_username:  gshahane
  twitter_username: simplygary
  #facebook_url:     https://www.facebook.com/heiswayi.nrird

# Disqus comment settings
disqus_enabled:     false
disqus_shortname:   gshahane-github-io

# GA
google_analytics_code: UA-98175267-1

# Build settings
source:             ./
destination:        ./_site
permalink:          /:year/:title
markdown:           kramdown
highlighter:        rouge
timezone:           America/New_York
exclude:            ["README.md", "LICENSE.md", "CHANGELOG.md"]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/scss
  style:            compressed # expanded

gems:
  - jekyll-sitemap
